import { useState, useEffect, useRef, useCallback, useMemo, createContext, useContext } from "react";
import {
  Play, Pencil, Eye, EyeOff, Grid3X3, Undo2, Redo2, Save, Upload, Share2,
  Type, Image, Trash2, Link2, Unlink, Camera, CameraOff,
  Plus, Minus, Move, ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  Layers, Download, X, Copy, ZoomIn, ZoomOut, MousePointer, Settings, Menu,
  Maximize2, Sun, Moon, Cloud, CloudOff, ExternalLink, RotateCw,
  FlipHorizontal, FlipVertical, Check, Volume2, VolumeX, Palette,
  HelpCircle, Sliders, Bold, Italic, Underline, Strikethrough, Search,
  Globe, Lock, ClipboardCopy, User
} from "lucide-react";

/* ═══ 1: SUPABASE (hardcoded for all users) ═══ */
const SB_URL = "https://hnrkgqjedimvbnvvetwh.supabase.co";
const SB_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhucmtncWplZGltdmJudnZldHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NDg3NzEsImV4cCI6MjA5MDAyNDc3MX0.d6MHuoWFshhTlKy_LJWOLjJU5UcMWeUPj924dqllmWQ";

/* ═══ 2: CONSTANTS ═══ */
const RW=1600,RH=1200,GS=32,MIN_Z=0.15,MAX_Z=4,IR=52;
const L={BG:0,OBJ:1,PL:2};
const BT={PE:"pressE",FT:"floorToggle",FH:"floorHold"};
let _u=Date.now();const uid=()=>`o${_u++}_${Math.random().toString(36).slice(2,6)}`;
const FONTS=[{l:"Sans-serif",v:"sans-serif"},{l:"Serif",v:"serif"},{l:"Monospace",v:"monospace"},{l:"Georgia",v:"Georgia,serif"},{l:"Palatino",v:"'Palatino Linotype',serif"},{l:"Times",v:"'Times New Roman',serif"},{l:"Courier",v:"'Courier New',monospace"},{l:"Verdana",v:"Verdana,sans-serif"},{l:"Trebuchet",v:"'Trebuchet MS',sans-serif"},{l:"Comic Sans",v:"'Comic Sans MS',cursive"},{l:"Impact",v:"Impact,sans-serif"}];

/* ═══ 3: THEMES ═══ */
const TH={
  light:{label:"Light",bg:"#f5f5f8",sf:"#fff",sfA:"#f0f0f5",bd:"#dddde6",bdL:"#e8e8f0",tx:"#1a1a2e",txD:"#5a5a72",txM:"#9999aa",ac:"#0087a8",acD:"rgba(0,135,168,0.08)",acB:"rgba(0,135,168,0.3)",wn:"#d97706",wnD:"rgba(217,119,6,0.08)",dg:"#dc2626",dgD:"rgba(220,38,38,0.06)",sc:"#16a34a",scD:"rgba(22,163,74,0.06)",cv:"#e4e4ec",bBg:"rgba(0,0,0,0.03)",bBd:"rgba(0,0,0,0.08)",gL:"rgba(0,0,0,0.06)"},
  dark:{label:"Dark",bg:"#0d0d18",sf:"#13131f",sfA:"#191928",bd:"#222236",bdL:"#2a2a42",tx:"#e0e0ec",txD:"#8888a0",txM:"#555570",ac:"#00d4f5",acD:"rgba(0,212,245,0.1)",acB:"rgba(0,212,245,0.3)",wn:"#fbbf24",wnD:"rgba(251,191,36,0.1)",dg:"#ef4444",dgD:"rgba(239,68,68,0.08)",sc:"#22c55e",scD:"rgba(34,197,94,0.08)",cv:"#0f0f1e",bBg:"rgba(255,255,255,0.04)",bBd:"rgba(255,255,255,0.08)",gL:"rgba(255,255,255,0.04)"},
  ocean:{label:"Ocean",bg:"#0b1628",sf:"#0f1d33",sfA:"#132440",bd:"#1a3050",bdL:"#204060",tx:"#d0e8ff",txD:"#7aa8cc",txM:"#4a7090",ac:"#00bcd4",acD:"rgba(0,188,212,0.12)",acB:"rgba(0,188,212,0.35)",wn:"#ff9800",wnD:"rgba(255,152,0,0.1)",dg:"#f44336",dgD:"rgba(244,67,54,0.08)",sc:"#4caf50",scD:"rgba(76,175,80,0.08)",cv:"#081220",bBg:"rgba(255,255,255,0.04)",bBd:"rgba(255,255,255,0.06)",gL:"rgba(100,180,255,0.05)"},
  forest:{label:"Forest",bg:"#0f1a0f",sf:"#152015",sfA:"#1a281a",bd:"#2a3a2a",bdL:"#354535",tx:"#d4e8d0",txD:"#88aa84",txM:"#557755",ac:"#66bb6a",acD:"rgba(102,187,106,0.12)",acB:"rgba(102,187,106,0.35)",wn:"#ffb74d",wnD:"rgba(255,183,77,0.1)",dg:"#e57373",dgD:"rgba(229,115,115,0.08)",sc:"#81c784",scD:"rgba(129,199,132,0.08)",cv:"#0a140a",bBg:"rgba(255,255,255,0.04)",bBd:"rgba(255,255,255,0.06)",gL:"rgba(100,200,100,0.05)"},
  sunset:{label:"Sunset",bg:"#1a0f0a",sf:"#241410",sfA:"#2e1a14",bd:"#4a2820",bdL:"#5a3428",tx:"#f0d8cc",txD:"#c09080",txM:"#806050",ac:"#ff7043",acD:"rgba(255,112,67,0.12)",acB:"rgba(255,112,67,0.35)",wn:"#ffd54f",wnD:"rgba(255,213,79,0.1)",dg:"#ef5350",dgD:"rgba(239,83,80,0.08)",sc:"#66bb6a",scD:"rgba(102,187,106,0.08)",cv:"#140a06",bBg:"rgba(255,255,255,0.04)",bBd:"rgba(255,255,255,0.06)",gL:"rgba(255,150,100,0.05)"},
  lavender:{label:"Lavender",bg:"#f5f0fa",sf:"#fff",sfA:"#f0eaf8",bd:"#d8d0e8",bdL:"#e4ddf0",tx:"#2a1a40",txD:"#6a5a80",txM:"#9990aa",ac:"#7c4dff",acD:"rgba(124,77,255,0.08)",acB:"rgba(124,77,255,0.3)",wn:"#f59e0b",wnD:"rgba(245,158,11,0.08)",dg:"#e11d48",dgD:"rgba(225,29,72,0.06)",sc:"#059669",scD:"rgba(5,150,105,0.06)",cv:"#ece4f4",bBg:"rgba(100,50,200,0.03)",bBd:"rgba(100,50,200,0.08)",gL:"rgba(100,50,200,0.06)"}
};
const TC=createContext(TH.light);

/* ═══ 4: SOUND ═══ */
let _ac=null;function gac(){if(!_ac)_ac=new(window.AudioContext||window.webkitAudioContext)();return _ac}
function dSnd(t){try{const c=gac(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);const cfg={[BT.PE]:[660,"square",0.12,0.12],[BT.FT]:[440,"triangle",0.1,0.18],[BT.FH]:[330,"sine",0.08,0.25]};const[f,tp,vol,dur]=cfg[t]||cfg[BT.PE];o.frequency.value=f;o.type=tp;g.gain.setValueAtTime(vol,c.currentTime);g.gain.exponentialRampToValueAtTime(0.001,c.currentTime+dur);o.start(c.currentTime);o.stop(c.currentTime+dur+0.01)}catch{}}
function cSnd(b){try{const a=new Audio(b);a.volume=0.3;a.play().catch(()=>{})}catch{}}
function bSnd(b,m){if(m)return;b.customSound?cSnd(b.customSound):dSnd(b.buttonType)}

/* ═══ 5: GAME OBJECTS (OOP) ═══ */
class GO{
  constructor(p={}){this.id=p.id||uid();this.type=p.type||"base";this.x=p.x??100;this.y=p.y??100;this.width=p.width??64;this.height=p.height??64;this.rotation=p.rotation??0;this.scaleX=p.scaleX??1;this.scaleY=p.scaleY??1;this.zIndex=p.zIndex??0;this.layer=p.layer??L.OBJ;this.visible=p.visible!==undefined?p.visible:true;this.name=p.name||"Object";this.link=p.link||""}
  ctr(){return{x:this.x+this.width/2,y:this.y+this.height/2}}
  hits(wx,wy){return wx>=this.x&&wx<=this.x+this.width&&wy>=this.y&&wy<=this.y+this.height}
  snap(g){this.x=Math.round(this.x/g)*g;this.y=Math.round(this.y/g)*g}
  _tf(c){c.translate(this.x+this.width/2,this.y+this.height/2);c.rotate(this.rotation*Math.PI/180);c.scale(this.scaleX,this.scaleY)}
  _sl(c){c.strokeStyle="#00d4f5";c.lineWidth=2;c.setLineDash([6,3]);c.strokeRect(-this.width/2-4,-this.height/2-4,this.width+8,this.height+8);c.setLineDash([]);c.fillStyle="#00d4f5";const hw=this.width/2+4,hh=this.height/2+4;for(const[a,b]of[[-hw,-hh],[hw,-hh],[-hw,hh],[hw,hh]])c.fillRect(a-3,b-3,6,6)}
  draw(c,ed,sel,sh){c.save();this._tf(c);if(!this.visible&&sh)c.globalAlpha=0.3;else if(!this.visible){c.restore();return}c.fillStyle="#888";c.fillRect(-this.width/2,-this.height/2,this.width,this.height);if(sel)this._sl(c);c.restore()}
  toJSON(){return{id:this.id,type:this.type,x:this.x,y:this.y,width:this.width,height:this.height,rotation:this.rotation,scaleX:this.scaleX,scaleY:this.scaleY,zIndex:this.zIndex,layer:this.layer,visible:this.visible,name:this.name,link:this.link}}
}
class TxO extends GO{
  constructor(p={}){super({...p,type:"text"});this.text=p.text||"Hello";this.fontSize=p.fontSize??24;this.color=p.color||"#222";this.bgColor=p.bgColor||"";this.fontFamily=p.fontFamily||"sans-serif";this.bold=p.bold??false;this.italic=p.italic??false;this.underline=p.underline??false;this.strike=p.strike??false;this.name=p.name||"Text";this.width=p.width??Math.max(48,this.text.length*this.fontSize*0.55);this.height=p.height??(this.fontSize+20)}
  _fs(){return`${this.italic?"italic ":""}${this.bold?"bold ":""}${this.fontSize}px ${this.fontFamily}`}
  draw(c,ed,sel,sh){c.save();this._tf(c);if(!this.visible&&sh)c.globalAlpha=0.3;else if(!this.visible){c.restore();return}if(this.bgColor){c.fillStyle=this.bgColor;c.beginPath();c.roundRect(-this.width/2,-this.height/2,this.width,this.height,4);c.fill()}else if(ed){c.fillStyle="rgba(128,128,128,0.05)";c.fillRect(-this.width/2,-this.height/2,this.width,this.height)}c.fillStyle=this.color;c.font=this._fs();c.textAlign="center";c.textBaseline="middle";const ws=this.text.split(' '),lh=this.fontSize*1.25,ls=[];let cu='';for(const w of ws){const t=cu?cu+' '+w:w;if(c.measureText(t).width>this.width-10&&cu){ls.push(cu);cu=w}else cu=t}if(cu)ls.push(cu);const sy=-ls.length*lh/2+lh/2;ls.forEach((ln,i)=>{const y=sy+i*lh;c.fillText(ln,0,y);const tw=c.measureText(ln).width;if(this.underline){c.beginPath();c.moveTo(-tw/2,y+this.fontSize*0.4);c.lineTo(tw/2,y+this.fontSize*0.4);c.strokeStyle=this.color;c.lineWidth=Math.max(1,this.fontSize/16);c.stroke()}if(this.strike){c.beginPath();c.moveTo(-tw/2,y);c.lineTo(tw/2,y);c.strokeStyle=this.color;c.lineWidth=Math.max(1,this.fontSize/16);c.stroke()}});if(sel)this._sl(c);c.restore()}
  toJSON(){return{...super.toJSON(),text:this.text,fontSize:this.fontSize,color:this.color,bgColor:this.bgColor,fontFamily:this.fontFamily,bold:this.bold,italic:this.italic,underline:this.underline,strike:this.strike}}
}
class ImO extends GO{
  constructor(p={}){super({...p,type:"image"});this.src=p.src||"";this._i=null;this._ok=false;this.name=p.name||"Image";if(this.src)this._ld()}
  _ld(){this._i=new window.Image();this._i.crossOrigin="anonymous";this._i.onload=()=>{this._ok=true};this._i.src=this.src}
  draw(c,ed,sel,sh){c.save();this._tf(c);if(!this.visible&&sh)c.globalAlpha=0.3;else if(!this.visible){c.restore();return}if(this._ok&&this._i)c.drawImage(this._i,-this.width/2,-this.height/2,this.width,this.height);else{c.fillStyle="#2a2a3a";c.fillRect(-this.width/2,-this.height/2,this.width,this.height);c.fillStyle="#666";c.font="11px monospace";c.textAlign="center";c.textBaseline="middle";c.fillText("Loading...",0,0)}if(sel)this._sl(c);c.restore()}
  toJSON(){return{...super.toJSON(),src:this.src}}
}
class BtO extends GO{
  constructor(p={}){super({...p,type:"button",width:p.width??44,height:p.height??44});this.buttonType=p.buttonType||BT.PE;this.linkedIds=p.linkedIds||[];this.isActive=p.isActive??false;this.visible=true;this.name=p.name||"Button";this.imgActive=p.imgActive||"";this.imgInactive=p.imgInactive||"";this.customSound=p.customSound||"";this._iA=null;this._iI=null;this._iAo=false;this._iIo=false;if(this.imgActive)this._lA();if(this.imgInactive)this._lI()}
  _lA(){this._iA=new window.Image();this._iA.crossOrigin="anonymous";this._iA.onload=()=>{this._iAo=true};this._iA.src=this.imgActive}
  _lI(){this._iI=new window.Image();this._iI.crossOrigin="anonymous";this._iI.onload=()=>{this._iIo=true};this._iI.src=this.imgInactive}
  tog(o,m){this.isActive=!this.isActive;this._sy(o);bSnd(this,m)}act(o,m){if(!this.isActive){this.isActive=true;this._sy(o);bSnd(this,m)}}dct(o){if(this.isActive){this.isActive=false;this._sy(o)}}
  _sy(o){for(const x of o)if(this.linkedIds.includes(x.id))x.visible=this.isActive}
  lk(id){if(!this.linkedIds.includes(id))this.linkedIds.push(id)}uk(id){this.linkedIds=this.linkedIds.filter(i=>i!==id)}
  draw(c,ed,sel){c.save();this._tf(c);const r=this.width/2;const uA=this.isActive&&this._iAo&&this._iA,uI=!this.isActive&&this._iIo&&this._iI;if(uA)c.drawImage(this._iA,-this.width/2,-this.height/2,this.width,this.height);else if(uI)c.drawImage(this._iI,-this.width/2,-this.height/2,this.width,this.height);else{const cols={[BT.PE]:this.isActive?"#22c55e":"#ef4444",[BT.FT]:this.isActive?"#84cc16":"#f59e0b",[BT.FH]:this.isActive?"#06b6d4":"#a855f7"};c.fillStyle=cols[this.buttonType]||"#888";c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.fill();const g=c.createRadialGradient(0,-r*.3,0,0,0,r);g.addColorStop(0,"rgba(255,255,255,0.25)");g.addColorStop(1,"rgba(255,255,255,0)");c.fillStyle=g;c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.fill();c.fillStyle="#fff";c.font=`bold ${Math.max(10,r*.5)}px monospace`;c.textAlign="center";c.textBaseline="middle";c.fillText({[BT.PE]:"E",[BT.FT]:"F",[BT.FH]:"H"}[this.buttonType]||"?",0,1)}if(sel){c.strokeStyle="#00d4f5";c.lineWidth=2.5;c.setLineDash([6,3]);c.beginPath();c.arc(0,0,r+6,0,Math.PI*2);c.stroke();c.setLineDash([])}c.restore()}
  toJSON(){return{...super.toJSON(),buttonType:this.buttonType,linkedIds:[...this.linkedIds],isActive:this.isActive,imgActive:this.imgActive,imgInactive:this.imgInactive,customSound:this.customSound}}
}
class Pl{
  constructor(p={}){this.x=p.x??400;this.y=p.y??300;this.size=p.size??26;this.speed=p.speed??3;this.color=p.color??"#00d4f5";this.dir="down";this.sprite1=p.sprite1||"";this.sprite2=p.sprite2||"";this._s1=null;this._s2=null;this._s1o=false;this._s2o=false;this._fr=0;this._tk=0;if(this.sprite1){this._s1=new window.Image();this._s1.onload=()=>{this._s1o=true};this._s1.src=this.sprite1}if(this.sprite2){this._s2=new window.Image();this._s2.onload=()=>{this._s2o=true};this._s2.src=this.sprite2}}
  bnds(){const h=this.size/2;return{x:this.x-h,y:this.y-h,width:this.size,height:this.size}}
  mv(dx,dy,rw,rh){const h=this.size/2;this.x=Math.max(h,Math.min(rw-h,this.x+dx));this.y=Math.max(h,Math.min(rh-h,this.y+dy));if(Math.abs(dx)>Math.abs(dy))this.dir=dx>0?"right":"left";else if(dy!==0)this.dir=dy>0?"down":"up";this._tk++;if(this._tk%10===0)this._fr=1-this._fr}
  draw(c){c.save();c.translate(this.x,this.y);if(this._s1o&&this._s1){c.scale(this.dir==="left"?-1:1,1);const im=(this._fr===1&&this._s2o&&this._s2)?this._s2:this._s1;c.drawImage(im,-this.size/2,-this.size/2,this.size,this.size)}else{c.fillStyle="rgba(0,0,0,0.1)";c.beginPath();c.ellipse(0,this.size*.4,this.size*.4,this.size*.12,0,0,Math.PI*2);c.fill();c.fillStyle=this.color;c.beginPath();c.arc(0,0,this.size/2,0,Math.PI*2);c.fill();c.strokeStyle="rgba(0,0,0,0.2)";c.lineWidth=1.5;c.stroke();c.fillStyle="#fff";const a=this.size*.2,dd={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]},[dx,dy]=dd[this.dir]||[0,1],t=this.size*.3;c.beginPath();c.moveTo(dx*t,dy*t);c.lineTo(dx*t-dy*a*.5-dx*a,dy*t+dx*a*.5-dy*a);c.lineTo(dx*t+dy*a*.5-dx*a,dy*t-dx*a*.5-dy*a);c.closePath();c.fill()}c.restore()}
  toJSON(){return{x:this.x,y:this.y,size:this.size,speed:this.speed,color:this.color,sprite1:this.sprite1,sprite2:this.sprite2}}
}

/* ═══ 6: ROOM + TUTORIAL ═══ */
class Rm{
  constructor(p={}){this.width=p.width??RW;this.height=p.height??RH;this.gridSize=p.gridSize??GS;this.gridOn=p.gridOn??false;this.bgColor=p.bgColor||"#ffffff";this.roomName=p.roomName||"My Room";this.objects=p.objects||[];this.player=p.player||new Pl({x:this.width/2,y:this.height/2});this.soundMuted=p.soundMuted??false}
  add(o){this.objects.push(o)}rm(id){for(const o of this.objects)if(o instanceof BtO)o.uk(id);this.objects=this.objects.filter(o=>o.id!==id)}find(id){return this.objects.find(o=>o.id===id)}ua(id){for(const o of this.objects)if(o instanceof BtO)o.uk(id)}
  srt(){return[...this.objects].sort((a,b)=>a.layer!==b.layer?a.layer-b.layer:a.zIndex-b.zIndex)}hit(wx,wy){return this.srt().reverse().find(o=>o.hits(wx,wy))||null}
  dup(id){const o=this.find(id);if(!o)return null;const j=o.toJSON();j.id=uid();j.x+=20;j.y+=20;j.name+=" copy";const n=Rm._mk(j);this.objects.push(n);return n}
  toJSON(){return{width:this.width,height:this.height,gridSize:this.gridSize,gridOn:this.gridOn,bgColor:this.bgColor,roomName:this.roomName,objects:this.objects.map(o=>o.toJSON()),player:this.player.toJSON(),soundMuted:this.soundMuted}}
  static _mk(o){switch(o.type){case"text":return new TxO(o);case"image":return new ImO(o);case"button":return new BtO(o);default:return new GO(o)}}
  static from(d){return new Rm({...d,objects:(d.objects||[]).map(Rm._mk),player:new Pl(d.player||{})})}
}
function mkTut(){
  const w=1600,h=1200;
  const tx=(id,x,y,ww,hh,text,o={})=>new TxO({id,x,y,width:ww,height:hh,text,fontSize:o.fs||13,color:o.c||"#333",bgColor:o.bg||"#fffde7",name:o.n||text.slice(0,20),zIndex:o.z||5,...o});
  const os=[
    tx("t0",w/2-200,30,400,46,"🏠 Welcome to Room Builder!",{fs:26,c:"#1a1a2e",bg:"#e0f7fa",n:"Title"}),
    tx("t0b",w/2-140,82,280,26,"Walk with WASD. Explore!",{fs:14,c:"#666",bg:"",n:"Subtitle"}),
    // Top-left toolbar
    tx("tl1",15,125,130,44,"⬆ Play / Edit\nSwitch modes",{bg:"#e8f5e9",n:"Mode"}),
    tx("tl2",155,125,120,44,"⬆ Camera\nFollow / Fixed",{bg:"#e3f2fd",n:"Camera"}),
    tx("tl3",285,125,105,44,"⬆ Grid\nSnap on/off",{bg:"#f3e5f5",n:"Grid"}),
    tx("tl4",400,125,115,44,"⬆ Show Hidden\nSee invisible objs",{bg:"#fce4ec",n:"Hidden"}),
    tx("tl5",525,125,110,44,"⬆ Undo/Redo\nCtrl+Z / Ctrl+Y",{bg:"#fff3e0",n:"Undo"}),
    tx("tl6",645,125,110,44,"⬆ Zoom\nScroll or +/−",{bg:"#e0f2f1",n:"Zoom"}),
    // Top-right toolbar
    tx("tr1",1090,125,120,44,"⬆ Settings\nThemes & player",{bg:"#ede7f6",n:"Settings"}),
    tx("tr2",1220,125,110,44,"⬆ Save\nLocal / export",{bg:"#e8eaf6",n:"Save"}),
    tx("tr3",1340,125,120,44,"⬆ Share\nCloud upload",{bg:"#e1f5fe",n:"Share"}),
    // Sidebar
    tx("sl1",15,200,190,32,"⬅ Add Tab: Place objects",{bg:"#c8e6c9",n:"Add Tab"}),
    tx("sl2",15,240,190,32,"⬅ Props Tab: Edit selected",{bg:"#dcedc8",n:"Props Tab"}),
    tx("sl3",15,280,200,32,"⬅ Object List at bottom",{bg:"#f0f4c3",n:"Obj List"}),
    // Movement & camera
    tx("mv",15,340,200,44,"🎮 WASD / Arrows to move\n📱 D-pad on mobile",{bg:"#bbdefb",n:"Move"}),
    tx("cm",15,395,200,44,"📷 Follow = tracks player\nFixed = drag to pan",{bg:"#f8bbd0",n:"Camera Info"}),
    // Buttons demo
    tx("bd",520,195,360,32,"Interactive Buttons — Try!",{fs:18,c:"#1a1a2e",bg:"#f3e5f5",n:"Btn Title"}),
    tx("be1",520,240,240,28,"🔴 Walk near, press E ➡",{bg:"#ffebee",n:"PE Label"}),
    new BtO({id:"bE",x:780,y:236,buttonType:BT.PE,linkedIds:["bEs"],name:"Demo Press E"}),
    tx("bEs",520,275,280,30,"🎉 Revealed by pressing E!",{c:"#16a34a",bg:"#dcfce7",n:"PE Secret",visible:false}),
    tx("bf1",520,325,240,28,"🟠 Walk onto this ➡",{bg:"#fff8e1",n:"FT Label"}),
    new BtO({id:"bF",x:780,y:321,width:48,height:48,buttonType:BT.FT,linkedIds:["bFs"],name:"Demo Floor Toggle"}),
    tx("bFs",520,360,280,30,"Toggled by stepping on!",{c:"#d97706",bg:"#fef3c7",n:"FT Secret",visible:false}),
    tx("bh1",520,410,240,28,"🟣 Stand on this ➡",{bg:"#f3e5f5",n:"FH Label"}),
    new BtO({id:"bH",x:780,y:406,width:48,height:48,buttonType:BT.FH,linkedIds:["bHs"],name:"Demo Floor Hold"}),
    tx("bHs",520,445,280,30,"Only while standing!",{c:"#7c3aed",bg:"#ede9fe",n:"FH Secret",visible:false}),
    // Features (2 columns)
    tx("f1",520,500,170,26,"✨ Images & GIFs",{bg:"#e8eaf6",n:"F1"}),
    tx("f2",520,532,170,26,"🖼 Button image states",{bg:"#e8eaf6",n:"F2"}),
    tx("f3",520,564,170,26,"🔊 Custom button SFX",{bg:"#e8eaf6",n:"F3"}),
    tx("f4",520,596,170,26,"🔗 Embed URLs",{bg:"#e8eaf6",n:"F4"}),
    tx("f5",700,500,170,26,"🎨 6 color themes",{bg:"#fce4ec",n:"F5"}),
    tx("f6",700,532,170,26,"👤 Custom sprites",{bg:"#fce4ec",n:"F6"}),
    tx("f7",700,564,170,26,"📐 Grid, layers, z-index",{bg:"#fce4ec",n:"F7"}),
    tx("f8",700,596,170,26,"☁ Cloud sharing",{bg:"#fce4ec",n:"F8"}),
    tx("f9",520,628,170,26,"✏ Bold/Italic/Underline",{bg:"#e0f2f1",n:"F9"}),
    tx("f10",700,628,170,26,"🔍 Browse & search rooms",{bg:"#e0f2f1",n:"F10"}),
    // Tips
    tx("tp1",15,470,210,26,"💡 Delete = remove object",{bg:"#fff3e0",n:"T1"}),
    tx("tp2",15,502,210,26,"💡 Ctrl+D = duplicate",{bg:"#fff3e0",n:"T2"}),
    tx("tp3",15,534,210,26,"💡 Escape = deselect",{bg:"#fff3e0",n:"T3"}),
    tx("tp4",15,566,210,26,"💡 Link buttons via Props",{bg:"#fff3e0",n:"T4"}),
    // Editor guide
    tx("eg",240,340,240,60,"✏ EDITOR MODE:\n1. Add objects\n2. Drag to position\n3. Edit in Props tab",{bg:"#e1f5fe",n:"Editor Guide"}),
    tx("st",w/2-60,h/2+30,120,24,"↑ Start here",{fs:13,c:"#0087a8",bg:"rgba(0,135,168,0.08)",n:"Start"}),
  ];
  return new Rm({width:w,height:h,roomName:"Tutorial Room",objects:os,player:new Pl({x:w/2,y:h/2-10,speed:3}),bgColor:"#f8f9fc"});
}
class Hi{constructor(m=60){this.u=[];this.r=[];this.m=m}push(j){this.u.push(JSON.stringify(j));if(this.u.length>this.m)this.u.shift();this.r=[]}undo(c){if(!this.u.length)return null;this.r.push(JSON.stringify(c));return JSON.parse(this.u.pop())}redo(c){if(!this.r.length)return null;this.u.push(JSON.stringify(c));return JSON.parse(this.r.pop())}get canUndo(){return this.u.length>0}get canRedo(){return this.r.length>0}}

/* ═══ 7: CLOUD ═══ */
class CS{
  constructor(u,k){this.url=u?.replace(/\/$/,"");this.key=k;this.bk="room-assets"}
  get ok(){return!!(this.url&&this.key&&!this.url.includes("YOUR_PROJECT"))}
  _h(ct){const h={Authorization:`Bearer ${this.key}`,apikey:this.key};if(ct)h["Content-Type"]=ct;return h}
  async upB(d,n){const r=await fetch(d);const b=await r.blob();const e=b.type.split("/")[1]||"bin";const p=`${Date.now()}_${n}.${e}`;const res=await fetch(`${this.url}/storage/v1/object/${this.bk}/${p}`,{method:"POST",headers:{...this._h(b.type),"x-upsert":"true"},body:b});if(!res.ok)throw new Error(await res.text());return`${this.url}/storage/v1/object/public/${this.bk}/${p}`}
  async _upA(d){for(let i=0;i<d.objects.length;i++){const o=d.objects[i];if(o.type==="image"&&o.src?.startsWith("data:"))o.src=await this.upB(o.src,`i${o.id}`);if(o.type==="button"){if(o.imgActive?.startsWith("data:"))o.imgActive=await this.upB(o.imgActive,`a${o.id}`);if(o.imgInactive?.startsWith("data:"))o.imgInactive=await this.upB(o.imgInactive,`b${o.id}`);if(o.customSound?.startsWith("data:"))o.customSound=await this.upB(o.customSound,`s${o.id}`)}}const p=d.player;if(p.sprite1?.startsWith("data:"))p.sprite1=await this.upB(p.sprite1,"sp1");if(p.sprite2?.startsWith("data:"))p.sprite2=await this.upB(p.sprite2,"sp2");return d}
  async save(rm,nick,pub){if(!this.ok)throw new Error("Not configured");let d=JSON.parse(JSON.stringify(rm.toJSON()));d=await this._upA(d);const id=crypto.randomUUID();const res=await fetch(`${this.url}/rest/v1/rooms`,{method:"POST",headers:{...this._h("application/json"),Prefer:"resolution=merge-duplicates"},body:JSON.stringify({id,name:d.roomName||"Untitled",nickname:nick||"Anonymous",data:d,is_public:pub!==false,visits:0})});if(!res.ok)throw new Error(await res.text());return id}
  async load(id){if(!this.ok)throw new Error("Not configured");const res=await fetch(`${this.url}/rest/v1/rooms?id=eq.${id}&select=*`,{headers:this._h("application/json")});if(!res.ok)throw new Error("Fail");const rows=await res.json();if(!rows.length)throw new Error("Not found");fetch(`${this.url}/rest/v1/rooms?id=eq.${id}`,{method:"PATCH",headers:this._h("application/json"),body:JSON.stringify({visits:(rows[0].visits||0)+1})}).catch(()=>{});return Rm.from(rows[0].data)}
  async list(n=30,q=""){if(!this.ok)return[];let u=`${this.url}/rest/v1/rooms?select=id,name,nickname,visits,created_at&is_public=eq.true&order=created_at.desc&limit=${n}`;if(q)u+=`&name=ilike.*${encodeURIComponent(q)}*`;const r=await fetch(u,{headers:this._h("application/json")});return r.ok?r.json():[]}
}

/* ═══ 8: LOCAL ═══ */
const Sr={save(r,s="room_default"){try{localStorage.setItem(s,JSON.stringify(r.toJSON()));return true}catch{return false}},load(s="room_default"){try{const d=localStorage.getItem(s);return d?Rm.from(JSON.parse(d)):null}catch{return null}},exp(r,fn){const b=new Blob([JSON.stringify(r.toJSON(),null,2)],{type:"application/json"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=fn||"room.json";a.click();URL.revokeObjectURL(u)},imp(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{try{res(Rm.from(JSON.parse(r.result)))}catch(e){rej(e)}};r.onerror=rej;r.readAsText(f)})}};

/* ═══ 9: RENDERER ═══ */
class Rd{constructor(cv){this.cv=cv;this.cx=cv.getContext("2d")}
  render({rm,camX,camY,zoom,ed,selId,showH,linking,hovId,vw,vh,T}){const c=this.cx,dp=window.devicePixelRatio||1;this.cv.width=vw*dp;this.cv.height=vh*dp;c.setTransform(dp,0,0,dp,0,0);c.fillStyle=T.cv;c.fillRect(0,0,vw,vh);c.save();c.translate(vw/2,vh/2);c.scale(zoom,zoom);c.translate(-camX,-camY);c.fillStyle=rm.bgColor;c.fillRect(0,0,rm.width,rm.height);c.strokeStyle=T.bd;c.lineWidth=2;c.strokeRect(0,0,rm.width,rm.height);if(rm.gridOn){c.strokeStyle=T.gL;c.lineWidth=1;for(let x=0;x<=rm.width;x+=rm.gridSize){c.beginPath();c.moveTo(x,0);c.lineTo(x,rm.height);c.stroke()}for(let y=0;y<=rm.height;y+=rm.gridSize){c.beginPath();c.moveTo(0,y);c.lineTo(rm.width,y);c.stroke()}}for(const o of rm.srt())o.draw(c,ed,o.id===selId,showH);if(ed)for(const o of rm.objects){if(!(o instanceof BtO)||!o.linkedIds.length)continue;const f=o.ctr();for(const lid of o.linkedIds){const t=rm.find(lid);if(!t)continue;const tc=t.ctr();const hi=o.id===selId||linking;c.strokeStyle=hi?"#fbbf24":"rgba(251,191,36,0.2)";c.lineWidth=hi?2.5:1.5;c.setLineDash([8,4]);c.beginPath();c.moveTo(f.x,f.y);c.lineTo(tc.x,tc.y);c.stroke();c.setLineDash([]);c.fillStyle=hi?"#fbbf24":"rgba(251,191,36,0.3)";c.beginPath();c.arc(tc.x,tc.y,4,0,Math.PI*2);c.fill()}}if(!ed){const px=rm.player.x,py=rm.player.y;for(const o of rm.objects){if(!(o instanceof BtO)||o.buttonType!==BT.PE)continue;const ct=o.ctr();if(Math.hypot(ct.x-px,ct.y-py)<IR+o.width/2){c.fillStyle="rgba(0,0,0,0.75)";c.beginPath();c.roundRect(ct.x-38,ct.y-o.height/2-34,76,24,6);c.fill();c.fillStyle="#fbbf24";c.font="bold 11px monospace";c.textAlign="center";c.textBaseline="middle";c.fillText("⏎ Press E",ct.x,ct.y-o.height/2-22)}}for(const o of rm.objects){if(!o.link||!o.visible)continue;const ct=o.ctr();c.fillStyle="rgba(59,130,246,0.7)";c.beginPath();c.roundRect(ct.x-26,o.y-18,52,16,4);c.fill();c.fillStyle="#fff";c.font="bold 9px sans-serif";c.textAlign="center";c.textBaseline="middle";c.fillText("🔗 Click",ct.x,o.y-10)}}rm.player.draw(c);if(ed&&linking&&hovId){const h=rm.find(hovId);if(h&&h.type!=="button"){c.strokeStyle="#fbbf24";c.lineWidth=3;c.setLineDash([5,5]);c.strokeRect(h.x-3,h.y-3,h.width+6,h.height+6);c.setLineDash([])}}c.restore()}
  s2w(sx,sy,cx,cy,z,vw,vh){return{wx:(sx-vw/2)/z+cx,wy:(sy-vh/2)/z+cy}}
}

/* ═══ 10: UI COMPONENTS ═══ */
function Btn({children,active,onClick,title,style,className=""}){const T=useContext(TC);return(<button onClick={onClick} title={title} className={`flex items-center justify-center gap-1.5 px-2 py-1.5 rounded-md text-xs font-medium transition-all hover:brightness-110 active:scale-95 ${className}`} style={{background:active?T.acD:T.bBg,border:`1px solid ${active?T.acB:T.bBd}`,color:active?T.ac:T.txD,...style}}>{children}</button>)}
function SR({label,value,onChange,min,max,step=1}){const T=useContext(TC);return(<div className="space-y-0.5"><div className="flex items-center justify-between"><span className="text-xs" style={{color:T.txD}}>{label}</span><input type="number" value={value} min={min} max={max} step={step} className="w-16 px-1 py-0.5 rounded text-right text-xs outline-none" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}} onChange={e=>onChange(parseFloat(e.target.value)||0)}/></div><input type="range" min={min} max={max} step={step} value={value} className="w-full h-1.5 rounded-full appearance-none cursor-pointer" style={{background:T.bd,accentColor:T.ac}} onChange={e=>onChange(parseFloat(e.target.value))}/></div>)}
function rF(a){return new Promise(r=>{const i=document.createElement("input");i.type="file";i.accept=a;i.onchange=()=>{const f=i.files?.[0];if(!f){r(null);return}const rd=new FileReader();rd.onload=()=>r({data:rd.result,name:f.name});rd.readAsDataURL(f)};i.click()})}
function iD(s){return new Promise(r=>{const i=new window.Image();i.onload=()=>r({w:i.width,h:i.height});i.onerror=()=>r({w:200,h:200});i.src=s})}
function Sec({title,children}){const T=useContext(TC);return(<div className="space-y-1.5"><p className="font-semibold uppercase tracking-wider" style={{color:T.txM,fontSize:9}}>{title}</p>{children}</div>)}
function Toast({msg,type="info",onDone}){const T=useContext(TC);useEffect(()=>{const t=setTimeout(onDone,3000);return()=>clearTimeout(t)},[onDone]);return(<div className="fixed top-4 left-1/2 -translate-x-1/2 z-[100] px-4 py-2 rounded-lg text-sm font-medium shadow-xl flex items-center gap-2" style={{background:T.sf,border:`1px solid ${T.bd}`,color:T.tx}}><div className="w-2 h-2 rounded-full" style={{background:{info:T.ac,error:T.dg,success:T.sc}[type]||T.ac}}/>{msg}</div>)}
function DPad({onDir}){const T=useContext(TC);const bc="w-12 h-12 rounded-xl flex items-center justify-center active:scale-90 select-none";const bs={background:T.acD,border:`1px solid ${T.acB}`};const h=d=>e=>{e.preventDefault();onDir(d,true)};const r=d=>e=>{e.preventDefault();onDir(d,false)};return(<div className="fixed bottom-6 left-6 z-50 select-none" style={{touchAction:"none"}}><div className="grid grid-cols-3 gap-1" style={{width:156}}><div/><button className={bc} style={bs} onTouchStart={h("up")} onTouchEnd={r("up")}><ChevronUp size={22} color={T.ac}/></button><div/><button className={bc} style={bs} onTouchStart={h("left")} onTouchEnd={r("left")}><ChevronLeft size={22} color={T.ac}/></button><div className="w-12 h-12 rounded-xl flex items-center justify-center" style={{background:T.bBg}}><Move size={14} color={T.txM}/></div><button className={bc} style={bs} onTouchStart={h("right")} onTouchEnd={r("right")}><ChevronRight size={22} color={T.ac}/></button><div/><button className={bc} style={bs} onTouchStart={h("down")} onTouchEnd={r("down")}><ChevronDown size={22} color={T.ac}/></button><div/></div><button className="mt-2 w-full h-11 rounded-xl font-bold text-sm tracking-widest select-none active:scale-95" style={{background:T.wnD,border:`1px solid ${T.wn}`,color:T.wn}} onTouchStart={e=>{e.preventDefault();onDir("interact",true)}} onTouchEnd={e=>{e.preventDefault();onDir("interact",false)}}>⏎ INTERACT</button></div>)}

/* Property Panel */
function PP({obj,room,onChange:ch,onDel,onUA,linking,onTL}){const T=useContext(TC);if(!obj)return(<div className="p-4 flex flex-col items-center h-32 justify-center" style={{color:T.txM}}><MousePointer size={20} className="mb-2 opacity-40"/><p className="text-xs">Click to select</p></div>);const c=(k,v)=>ch(obj.id,k,v);
  return(<div className="p-3 space-y-3 text-xs overflow-y-auto" style={{maxHeight:"calc(100vh-160px)"}}>
    <div><input value={obj.name} className="w-full px-2 py-1.5 rounded text-sm font-semibold outline-none" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}} onChange={e=>c("name",e.target.value)}/><p className="mt-0.5 uppercase tracking-widest font-semibold" style={{color:T.txM,fontSize:9}}>{obj.type}</p></div>
    {(obj.type==="text"||obj.type==="image")&&<Sec title="Link URL"><div className="flex gap-1"><input value={obj.link||""} placeholder="https://..." className="flex-1 px-2 py-1 rounded text-xs outline-none" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}} onChange={e=>c("link",e.target.value)}/>{obj.link&&<button onClick={()=>window.open(obj.link,"_blank")} className="p-1 rounded" style={{color:T.ac}}><ExternalLink size={12}/></button>}</div></Sec>}
    <Sec title="Transform"><SR label="X" value={obj.x} onChange={v=>c("x",v)} min={-200} max={room.width+200}/><SR label="Y" value={obj.y} onChange={v=>c("y",v)} min={-200} max={room.height+200}/><SR label="W" value={obj.width} onChange={v=>c("width",v)} min={8} max={2000}/><SR label="H" value={obj.height} onChange={v=>c("height",v)} min={8} max={2000}/><SR label="Rotation" value={obj.rotation} onChange={v=>c("rotation",v)} min={-180} max={180}/><SR label="Scale X" value={obj.scaleX} onChange={v=>c("scaleX",v)} min={-5} max={5} step={0.1}/><SR label="Scale Y" value={obj.scaleY} onChange={v=>c("scaleY",v)} min={-5} max={5} step={0.1}/><div className="flex gap-1 pt-1"><Btn onClick={()=>c("rotation",0)}><RotateCw size={11}/> 0°</Btn><Btn onClick={()=>c("scaleX",obj.scaleX*-1)}><FlipHorizontal size={11}/></Btn><Btn onClick={()=>c("scaleY",obj.scaleY*-1)}><FlipVertical size={11}/></Btn></div></Sec>
    <Sec title="Ordering"><label className="flex items-center justify-between"><span style={{color:T.txD}}>Layer</span><select value={obj.layer} className="px-1.5 py-0.5 rounded text-xs outline-none" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}} onChange={e=>c("layer",parseInt(e.target.value))}><option value={L.BG}>Background</option><option value={L.OBJ}>Objects</option></select></label><SR label="Z-Index" value={obj.zIndex} onChange={v=>c("zIndex",v)} min={-50} max={50}/></Sec>
    {obj.type==="text"&&<Sec title="Text"><textarea value={obj.text} rows={2} className="w-full px-2 py-1.5 rounded text-xs outline-none resize-y" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}} onChange={e=>c("text",e.target.value)}/><label className="flex items-center justify-between"><span style={{color:T.txD}}>Font</span><select value={obj.fontFamily} className="w-28 px-1 py-0.5 rounded text-xs outline-none" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx,fontFamily:obj.fontFamily}} onChange={e=>c("fontFamily",e.target.value)}>{FONTS.map(f=><option key={f.v} value={f.v} style={{fontFamily:f.v}}>{f.l}</option>)}</select></label><SR label="Size" value={obj.fontSize} onChange={v=>c("fontSize",v)} min={8} max={120}/><div className="flex gap-1">{[["bold",Bold],["italic",Italic],["underline",Underline],["strike",Strikethrough]].map(([k,Ic])=>(<button key={k} onClick={()=>c(k,!obj[k])} className="flex-1 py-1.5 rounded flex items-center justify-center" style={{background:obj[k]?T.acD:T.bg,border:`1px solid ${obj[k]?T.acB:T.bd}`,color:obj[k]?T.ac:T.txD}}><Ic size={13}/></button>))}</div><label className="flex items-center justify-between"><span style={{color:T.txD}}>Color</span><input type="color" value={obj.color} onChange={e=>c("color",e.target.value)} className="w-7 h-5 rounded cursor-pointer"/></label><label className="flex items-center justify-between"><span style={{color:T.txD}}>BG</span><div className="flex items-center gap-1">{obj.bgColor&&<button onClick={()=>c("bgColor","")} className="text-xs" style={{color:T.dg}}>✕</button>}<input type="color" value={obj.bgColor||"#fff"} onChange={e=>c("bgColor",e.target.value)} className="w-7 h-5 rounded cursor-pointer"/></div></label></Sec>}
    {obj.type==="button"&&<Sec title="Button"><label className="flex items-center justify-between"><span style={{color:T.txD}}>Type</span><select value={obj.buttonType} className="px-1.5 py-0.5 rounded text-xs outline-none" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}} onChange={e=>c("buttonType",e.target.value)}><option value={BT.PE}>Press E</option><option value={BT.FT}>Floor Toggle</option><option value={BT.FH}>Floor Hold</option></select></label><p className="font-semibold uppercase tracking-wider pt-1" style={{color:T.txM,fontSize:9}}>Images</p><div className="flex gap-2">{["Inactive","Active"].map((lbl,i)=>{const k=i===0?"imgInactive":"imgActive";const v=obj[k];return(<div key={k} className="flex-1"><p style={{color:T.txD,fontSize:10}}>{lbl}</p>{v?(<div className="relative group"><img src={v} alt="" className="w-full h-10 object-contain rounded" style={{background:T.bg}}/><button onClick={()=>c(k,"")} className="absolute top-0 right-0 p-0.5 rounded-bl opacity-0 group-hover:opacity-100" style={{background:T.dg}}><X size={9} color="#fff"/></button></div>):(<button onClick={async()=>{const r=await rF("image/*");if(r)c(k,r.data)}} className="w-full h-10 rounded flex items-center justify-center" style={{border:`1px dashed ${T.bd}`,color:T.txM,fontSize:10}}><Upload size={10}/>Upload</button>)}</div>)})}</div><p className="font-semibold uppercase tracking-wider pt-1" style={{color:T.txM,fontSize:9}}>Sound</p>{obj.customSound?<div className="flex items-center gap-1"><Volume2 size={12} color={T.sc}/><span style={{color:T.txD}}>Custom</span><button onClick={()=>c("customSound","")} className="ml-auto" style={{color:T.dg}}><X size={11}/></button></div>:<div className="flex items-center gap-1"><span style={{color:T.txM,fontSize:10}}>Default tone</span><button onClick={async()=>{const r=await rF("audio/*");if(r)c("customSound",r.data)}} className="ml-auto px-2 py-0.5 rounded text-xs" style={{border:`1px solid ${T.bd}`,color:T.txD}}><Upload size={10} className="inline mr-1"/>Upload</button></div>}<button onClick={onTL} className="w-full py-2 rounded-md text-xs font-semibold mt-1" style={{background:linking?T.wnD:T.acD,border:`1px solid ${linking?T.wn:T.acB}`,color:linking?T.wn:T.txD}}>{linking?"✓ Linking — Click targets":"🔗 Link to Objects"}</button><div className="pt-0.5"><p style={{color:T.txM}}>{obj.linkedIds.length} linked</p>{obj.linkedIds.map(lid=>{const lo=room.find(lid);return lo?<div key={lid} className="flex items-center justify-between py-0.5 pl-1"><span style={{color:T.txD}} className="truncate">{lo.name}</span><button onClick={()=>c("_unlink",lid)} style={{color:T.dg}}><X size={11}/></button></div>:null})}</div></Sec>}
    {obj.type!=="button"&&<label className="flex items-center justify-between px-1"><span style={{color:T.txD}}>Visible</span><button onClick={()=>c("visible",!obj.visible)} className="p-1 rounded" style={{background:obj.visible?T.scD:T.dgD}}>{obj.visible?<Eye size={13} color={T.sc}/>:<EyeOff size={13} color={T.dg}/>}</button></label>}
    <div className="space-y-1.5 pt-2" style={{borderTop:`1px solid ${T.bd}`}}><button onClick={()=>onUA(obj.id)} className="w-full py-1.5 rounded-md text-xs flex items-center justify-center gap-1.5" style={{background:T.wnD,border:`1px solid ${T.wn}30`,color:T.wn}}><Unlink size={11}/>Unlink All</button><button onClick={()=>onDel(obj.id)} className="w-full py-1.5 rounded-md text-xs flex items-center justify-center gap-1.5" style={{background:T.dgD,border:`1px solid ${T.dg}30`,color:T.dg}}><Trash2 size={11}/>Delete</button></div>
  </div>)}

/* Share Modal */
function SM({room,cloud,onClose,toast:dt,onLoad,pushH}){const T=useContext(TC);const[tab,setTab]=useState("share");const[nick,setNick]=useState(()=>localStorage.getItem("rb_nick")||"");const[rNm,setRNm]=useState(room.roomName);const[pub,setPub]=useState(true);const[saving,setSaving]=useState(false);const[sId,setSId]=useState(null);const[recent,setRecent]=useState([]);const[srch,setSrch]=useState("");const[sring,setSring]=useState(false);const[lId,setLId]=useState("");const[lding,setLding]=useState(false);
  const doSrch=useCallback(async(q="")=>{setSring(true);try{setRecent(await cloud.list(30,q))}catch{}setSring(false)},[cloud]);
  useEffect(()=>{if(cloud.ok)doSrch()},[cloud,doSrch]);
  const share=async()=>{if(!nick.trim()){dt("Enter a nickname","error");return}localStorage.setItem("rb_nick",nick);setSaving(true);try{const id=await cloud.save({...room,roomName:rNm},nick.trim(),pub);setSId(id);dt("Shared!","success")}catch(e){dt("Failed: "+e.message,"error")}setSaving(false)};
  const cpId=async id=>{const url=`${location.origin}${location.pathname}?room=${id}`;try{await navigator.clipboard.writeText(url);dt("Link copied!","success")}catch{try{await navigator.clipboard.writeText(id);dt("ID copied!","success")}catch{prompt("Copy:",url)}}};
  const ld=async id=>{setLding(true);try{pushH();onLoad(await cloud.load(id));dt("Loaded!","success");onClose()}catch(e){dt("Failed: "+e.message,"error")}setLding(false)};
  return(<div className="fixed inset-0 z-[90] flex items-center justify-center" onClick={onClose}><div className="absolute inset-0 bg-black/50"/><div className="relative rounded-xl shadow-2xl w-full max-w-lg mx-4 overflow-hidden" style={{background:T.sf,border:`1px solid ${T.bd}`}} onClick={e=>e.stopPropagation()}>
    <div className="flex items-center justify-between px-4 py-3" style={{borderBottom:`1px solid ${T.bd}`}}><div className="flex items-center gap-2"><Cloud size={16} color={T.ac}/><span className="font-semibold text-sm" style={{color:T.tx}}>Cloud</span></div><button onClick={onClose} style={{color:T.txM}}><X size={16}/></button></div>
    <div className="flex" style={{borderBottom:`1px solid ${T.bd}`}}>{[["share","Share"],["browse","Browse"],["load","Load ID"]].map(([id,l])=><button key={id} onClick={()=>setTab(id)} className="flex-1 py-2 text-xs font-medium" style={{color:tab===id?T.ac:T.txM,borderBottom:tab===id?`2px solid ${T.ac}`:"2px solid transparent"}}>{l}</button>)}</div>
    <div className="p-4 space-y-3 max-h-80 overflow-y-auto">
      {tab==="share"&&(!sId?<><p className="text-xs" style={{color:T.txD}}>Set your nickname and choose visibility.</p><label className="block"><span className="text-xs font-medium" style={{color:T.txD}}>Nickname</span><input value={nick} onChange={e=>setNick(e.target.value)} placeholder="Your name..." className="w-full mt-0.5 px-2.5 py-1.5 rounded-lg text-sm outline-none" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}}/></label><label className="block"><span className="text-xs font-medium" style={{color:T.txD}}>Room Name</span><input value={rNm} onChange={e=>setRNm(e.target.value)} className="w-full mt-0.5 px-2.5 py-1.5 rounded-lg text-sm outline-none" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}}/></label><div className="flex gap-2"><button onClick={()=>setPub(true)} className="flex-1 py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5" style={{background:pub?T.scD:T.bg,border:`1px solid ${pub?T.sc+"40":T.bd}`,color:pub?T.sc:T.txD}}><Globe size={12}/>Public</button><button onClick={()=>setPub(false)} className="flex-1 py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5" style={{background:!pub?T.wnD:T.bg,border:`1px solid ${!pub?T.wn+"40":T.bd}`,color:!pub?T.wn:T.txD}}><Lock size={12}/>Unlisted</button></div><p className="text-xs" style={{color:T.txM}}>{pub?"Visible in Browse tab.":"Only accessible via direct link."}</p><button onClick={share} disabled={saving} className="w-full py-2.5 rounded-lg text-sm font-semibold disabled:opacity-50" style={{background:T.acD,border:`1px solid ${T.acB}`,color:T.ac}}>{saving?"Uploading...":"Share"}</button></>:<div className="space-y-3"><div className="flex items-center gap-1.5 text-sm" style={{color:T.sc}}><Check size={16}/>Shared!</div><div className="p-3 rounded-lg flex items-center gap-2" style={{background:T.bg,border:`1px solid ${T.bd}`}}><div className="flex-1 text-xs break-all font-mono" style={{color:T.tx}}>{sId}</div><button onClick={()=>cpId(sId)} className="flex-shrink-0 p-1.5 rounded-md" style={{background:T.acD,color:T.ac}} title="Copy link"><ClipboardCopy size={14}/></button></div><p className="text-xs" style={{color:T.txM}}>{pub?"Public":"Unlisted"}</p><button onClick={()=>setSId(null)} className="text-xs underline" style={{color:T.txD}}>Share another</button></div>)}
      {tab==="browse"&&<><div className="flex gap-1.5"><div className="flex-1 relative"><Search size={14} className="absolute left-2 top-1/2 -translate-y-1/2" style={{color:T.txM}}/><input value={srch} onChange={e=>setSrch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")doSrch(srch)}} placeholder="Search..." className="w-full pl-8 pr-2 py-1.5 rounded-lg text-xs outline-none" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}}/></div><button onClick={()=>doSrch(srch)} className="px-3 py-1.5 rounded-lg text-xs font-semibold" style={{background:T.acD,border:`1px solid ${T.acB}`,color:T.ac}}>{sring?"...":"Go"}</button></div>{recent.length===0&&<p className="text-xs py-4 text-center" style={{color:T.txM}}>No public rooms.</p>}{recent.map(r=><div key={r.id} className="flex items-center gap-2 p-2.5 rounded-lg" style={{background:T.bg,border:`1px solid ${T.bd}`}}><div className="flex-1 min-w-0"><p className="text-sm font-medium truncate" style={{color:T.tx}}>{r.name}</p><p className="text-xs mt-0.5 flex items-center gap-2" style={{color:T.txM}}><span className="flex items-center gap-0.5"><User size={10}/>{r.nickname||"Anon"}</span><span>{r.visits||0} views</span><span>{new Date(r.created_at).toLocaleDateString()}</span></p></div><button onClick={()=>cpId(r.id)} className="p-1.5 rounded" title="Copy link" style={{color:T.txD}}><ClipboardCopy size={13}/></button><button onClick={()=>ld(r.id)} className="px-2.5 py-1 rounded-md text-xs font-semibold" style={{background:T.acD,color:T.ac}}>Open</button></div>)}</>}
      {tab==="load"&&<><p className="text-xs" style={{color:T.txD}}>Paste room ID or URL.</p><input value={lId} onChange={e=>setLId(e.target.value)} placeholder="ID or URL..." className="w-full px-3 py-2 rounded-lg text-sm outline-none" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}}/><button onClick={()=>{let id=lId.trim();if(id.includes("room="))id=id.split("room=")[1].split("&")[0];if(id)ld(id)}} disabled={lding||!lId.trim()} className="w-full py-2.5 rounded-lg text-sm font-semibold disabled:opacity-50" style={{background:T.acD,border:`1px solid ${T.acB}`,color:T.ac}}>{lding?"...":"Load"}</button></>}
    </div></div></div>)}

/* ═══ 11: MAIN APP ═══ */
export default function App(){
  const[tn,setTn]=useState(()=>localStorage.getItem("rb_theme")||"light");const T=TH[tn]||TH.light;
  const cloud=useMemo(()=>new CS(SB_URL,SB_KEY),[]);
  const[room,setRoom]=useState(()=>{if(!localStorage.getItem("rb_v")){localStorage.setItem("rb_v","1");return mkTut()}return Sr.load()||mkTut()});
  const[ed,setEd]=useState(false);const[selId,setSel]=useState(null);const[showH,setShowH]=useState(false);
  const[camF,setCamF]=useState(true);const[zoom,setZoom]=useState(1);const[camP,setCamP]=useState({x:RW/2,y:RH/2});
  const[lnk,setLnk]=useState(false);const[hovId,setHovId]=useState(null);
  const[toast,setToast]=useState(null);const[tT,setTT]=useState("info");
  const[showSv,setShowSv]=useState(false);const[showSh,setShowSh]=useState(false);const[showSt,setShowSt]=useState(false);
  const[mob,setMob]=useState(false);const[sb,setSb]=useState(true);const[tab,setTab]=useState("add");
  const[curP,setCurP]=useState(false);
  const cvR=useRef(null);const rdR=useRef(null);const rmR=useRef(room);const kR=useRef({});const hR=useRef(new Hi());const dR=useRef(null);const afR=useRef(null);const cR=useRef(null);const[vp,setVp]=useState({w:800,h:600});const fR=useRef(null);
  rmR.current=room;const dt=useCallback((m,t="info")=>{setToast(m);setTT(t)},[]);
  useEffect(()=>{setMob("ontouchstart"in window||navigator.maxTouchPoints>0)},[]);
  useEffect(()=>{const p=new URLSearchParams(location.search);const rid=p.get("room");if(rid&&cloud.ok)cloud.load(rid).then(r=>{setRoom(r);setCamP({x:r.width/2,y:r.height/2});dt("Loaded!","success");setEd(false)}).catch(()=>dt("Load failed","error"))},[]);
  useEffect(()=>{const el=cR.current;if(!el)return;const ro=new ResizeObserver(e=>{const{width:w,height:h}=e[0].contentRect;setVp({w,h})});ro.observe(el);return()=>ro.disconnect()},[]);
  useEffect(()=>{if(cvR.current)rdR.current=new Rd(cvR.current)},[]);
  useEffect(()=>{const kd=e=>{const k=e.key.toLowerCase();kR.current[k]=true;if((e.ctrlKey||e.metaKey)&&k==="z"&&!e.shiftKey){e.preventDefault();doU()}if((e.ctrlKey||e.metaKey)&&k==="z"&&e.shiftKey){e.preventDefault();doR()}if((e.ctrlKey||e.metaKey)&&k==="y"){e.preventDefault();doR()}if((e.ctrlKey||e.metaKey)&&k==="d"){e.preventDefault();dupS()}if(k==="e"&&!ed)intE();if((e.key==="Delete"||e.key==="Backspace")&&ed&&selId&&!["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName)){e.preventDefault();del(selId)}if(e.key==="Escape"){setLnk(false);setSel(null)}};const ku=e=>{kR.current[e.key.toLowerCase()]=false};window.addEventListener("keydown",kd);window.addEventListener("keyup",ku);return()=>{window.removeEventListener("keydown",kd);window.removeEventListener("keyup",ku)}},[ed,selId]);
  useEffect(()=>{let run=true;const loop=()=>{if(!run)return;const r=rmR.current,k=kR.current;if(!ed){let dx=0,dy=0;if(k.w||k.arrowup)dy-=r.player.speed;if(k.s||k.arrowdown)dy+=r.player.speed;if(k.a||k.arrowleft)dx-=r.player.speed;if(k.d||k.arrowright)dx+=r.player.speed;if(dx&&dy){dx*=.707;dy*=.707}if(dx||dy){r.player.mv(dx,dy,r.width,r.height);const pb=r.player.bnds();for(const o of r.objects){if(!(o instanceof BtO))continue;const ov=pb.x<o.x+o.width&&pb.x+pb.width>o.x&&pb.y<o.y+o.height&&pb.y+pb.height>o.y;if(o.buttonType===BT.FT){if(ov&&!o._w){o.tog(r.objects,r.soundMuted);o._w=true}else if(!ov)o._w=false}else if(o.buttonType===BT.FH){if(ov)o.act(r.objects,r.soundMuted);else o.dct(r.objects)}}}}const cx=camF?r.player.x:camP.x,cy=camF?r.player.y:camP.y;if(rdR.current)rdR.current.render({rm:r,camX:cx,camY:cy,zoom,ed,selId,showH,linking:lnk,hovId,vw:vp.w,vh:vp.h,T});afR.current=requestAnimationFrame(loop)};afR.current=requestAnimationFrame(loop);return()=>{run=false;if(afR.current)cancelAnimationFrame(afR.current)}},[ed,selId,showH,lnk,hovId,camF,camP,zoom,vp,T]);
  const pH=useCallback(()=>{hR.current.push(rmR.current.toJSON())},[]);
  const doU=useCallback(()=>{const p=hR.current.undo(rmR.current.toJSON());if(p){setRoom(Rm.from(p));setSel(null)}},[]);
  const doR=useCallback(()=>{const n=hR.current.redo(rmR.current.toJSON());if(n){setRoom(Rm.from(n));setSel(null)}},[]);
  const chg=useCallback((id,k,v)=>{pH();const r=rmR.current,o=r.find(id);if(!o)return;if(k==="_unlink"&&o instanceof BtO)o.uk(v);else o[k]=v;if(k==="imgActive"&&o instanceof BtO)o._lA();if(k==="imgInactive"&&o instanceof BtO)o._lI();if((k==="x"||k==="y")&&r.gridOn)o.snap(r.gridSize);setRoom(Rm.from(r.toJSON()))},[pH]);
  const addT=useCallback(()=>{pH();const r=rmR.current;const o=new TxO({x:r.width/2-80,y:r.height/2-20,text:"New Text",fontSize:24,color:"#333"});if(r.gridOn)o.snap(r.gridSize);r.add(o);setRoom(Rm.from(r.toJSON()));setSel(o.id);setTab("props")},[pH]);
  const addI=useCallback(async()=>{const res=await rF("image/png,image/jpeg,image/gif,image/webp");if(!res)return;pH();const r=rmR.current;const d=await iD(res.data);let w=d.w,h=d.h;if(w>400||h>400){const s=400/Math.max(w,h);w*=s;h*=s}const o=new ImO({x:r.width/2-w/2,y:r.height/2-h/2,width:w,height:h,src:res.data,name:res.name||"Image"});if(r.gridOn)o.snap(r.gridSize);r.add(o);setRoom(Rm.from(r.toJSON()));setSel(o.id);setTab("props")},[pH]);
  const addB=useCallback(bt=>{pH();const r=rmR.current;const o=new BtO({x:r.width/2-22,y:r.height/2-22,buttonType:bt});if(r.gridOn)o.snap(r.gridSize);r.add(o);setRoom(Rm.from(r.toJSON()));setSel(o.id);setTab("props")},[pH]);
  const del=useCallback(id=>{pH();rmR.current.rm(id);setRoom(Rm.from(rmR.current.toJSON()));setSel(null);setLnk(false)},[pH]);
  const ulnkA=useCallback(id=>{pH();rmR.current.ua(id);setRoom(Rm.from(rmR.current.toJSON()))},[pH]);
  const dupS=useCallback(()=>{if(!selId)return;pH();const n=rmR.current.dup(selId);if(n){setRoom(Rm.from(rmR.current.toJSON()));setSel(n.id)}},[selId,pH]);
  const intE=useCallback(()=>{const r=rmR.current;for(const o of r.objects){if(!(o instanceof BtO)||o.buttonType!==BT.PE)continue;const c=o.ctr();if(Math.hypot(c.x-r.player.x,c.y-r.player.y)<IR+o.width/2){o.tog(r.objects,r.soundMuted);break}}},[]);
  const chgR=useCallback((k,v)=>{setRoom(p=>{const d=p.toJSON();d[k]=v;return Rm.from(d)})},[]);
  const chgP=useCallback((k,v)=>{setRoom(p=>{const d=p.toJSON();d.player[k]=v;return Rm.from(d)})},[]);
  const w2s=useCallback((cx,cy)=>{if(!cvR.current||!rdR.current)return{wx:0,wy:0};const rect=cvR.current.getBoundingClientRect();const cX=camF?rmR.current.player.x:camP.x;const cY=camF?rmR.current.player.y:camP.y;return rdR.current.s2w(cx-rect.left,cy-rect.top,cX,cY,zoom,vp.w,vp.h)},[camF,camP,zoom,vp]);
  const onDn=useCallback(e=>{const{wx,wy}=w2s(e.clientX,e.clientY);const r=rmR.current,hit=r.hit(wx,wy);if(!ed){if(hit&&hit.link&&hit.visible)window.open(hit.link,"_blank");return}if(lnk&&selId){if(hit&&hit.type!=="button"&&hit.id!==selId){pH();const b=r.find(selId);if(b instanceof BtO){if(b.linkedIds.includes(hit.id))b.uk(hit.id);else b.lk(hit.id);setRoom(Rm.from(r.toJSON()))}}return}if(hit){setSel(hit.id);setTab("props");pH();dR.current={id:hit.id,ox:wx-hit.x,oy:wy-hit.y}}else{setSel(null);setLnk(false);if(!camF)dR.current={id:null,scx:camP.x,scy:camP.y,smx:e.clientX,smy:e.clientY}}},[ed,lnk,selId,w2s,camF,camP,pH]);
  const onMv=useCallback(e=>{const{wx,wy}=w2s(e.clientX,e.clientY);if(!ed){const hit=rmR.current.hit(wx,wy);setCurP(!!(hit&&hit.link&&hit.visible));return}if(lnk){const h=rmR.current.hit(wx,wy);setHovId(h?.id||null)}if(!dR.current)return;if(dR.current.id){const o=rmR.current.find(dR.current.id);if(o){let nx=wx-dR.current.ox,ny=wy-dR.current.oy;if(rmR.current.gridOn){nx=Math.round(nx/rmR.current.gridSize)*rmR.current.gridSize;ny=Math.round(ny/rmR.current.gridSize)*rmR.current.gridSize}o.x=nx;o.y=ny}}else if(dR.current.scx!==undefined)setCamP({x:dR.current.scx-(e.clientX-dR.current.smx)/zoom,y:dR.current.scy-(e.clientY-dR.current.smy)/zoom})},[ed,lnk,w2s,zoom]);
  const onUp=useCallback(()=>{if(dR.current?.id)setRoom(Rm.from(rmR.current.toJSON()));dR.current=null},[]);
  const onWh=useCallback(e=>{e.preventDefault();setZoom(z=>Math.max(MIN_Z,Math.min(MAX_Z,z-e.deltaY*0.001)))},[]);
  const dpH=useCallback((d,p)=>{kR.current[{up:"w",down:"s",left:"a",right:"d",interact:"e"}[d]]=p;if(d==="interact"&&p&&!ed)intE()},[ed,intE]);
  const selObj=useMemo(()=>selId?room.find(selId):null,[room,selId]);
  return(<TC.Provider value={T}><div className="w-full h-screen flex flex-col overflow-hidden" style={{background:T.bg,fontFamily:"'DM Mono','JetBrains Mono','Fira Code',ui-monospace,monospace",color:T.tx}}>
    <input ref={fR} type="file" accept=".json" className="hidden" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{pH();setRoom(await Sr.imp(f));dt("Imported!","success")}catch{dt("Failed","error")}e.target.value=""}}/>
    {toast&&<Toast msg={toast} type={tT} onDone={()=>setToast(null)}/>}
    {showSh&&cloud.ok&&<SM room={room} cloud={cloud} onClose={()=>setShowSh(false)} toast={dt} onLoad={r=>{setRoom(r);setCamP({x:r.width/2,y:r.height/2})}} pushH={pH}/>}
    {showSt&&<div className="fixed inset-0 z-[90] flex items-center justify-center" onClick={()=>setShowSt(false)}><div className="absolute inset-0 bg-black/50"/><div className="relative rounded-xl shadow-2xl w-full max-w-md mx-4 max-h-[85vh] overflow-y-auto" style={{background:T.sf,border:`1px solid ${T.bd}`}} onClick={e=>e.stopPropagation()}>
      <div className="flex items-center justify-between px-4 py-3 sticky top-0 z-10" style={{background:T.sf,borderBottom:`1px solid ${T.bd}`}}><div className="flex items-center gap-2"><Settings size={16} color={T.ac}/><span className="font-semibold text-sm" style={{color:T.tx}}>Settings</span></div><button onClick={()=>setShowSt(false)} style={{color:T.txM}}><X size={16}/></button></div>
      <div className="p-4 space-y-4">
        <Sec title="Theme"><div className="grid grid-cols-3 gap-1.5">{Object.entries(TH).map(([k,v])=><button key={k} onClick={()=>{setTn(k);localStorage.setItem("rb_theme",k)}} className="py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1" style={{background:tn===k?T.acD:T.bg,border:`1px solid ${tn===k?T.acB:T.bd}`,color:tn===k?T.ac:T.txD}}><div className="w-3 h-3 rounded-full" style={{background:v.ac}}/>{v.label}</button>)}</div></Sec>
        <Sec title="Player"><SR label="Speed" value={room.player.speed} onChange={v=>chgP("speed",v)} min={1} max={10} step={0.5}/><SR label="Size" value={room.player.size} onChange={v=>chgP("size",v)} min={12} max={60}/><label className="flex items-center justify-between"><span className="text-xs" style={{color:T.txD}}>Color</span><input type="color" value={room.player.color} onChange={e=>chgP("color",e.target.value)} className="w-7 h-5 rounded cursor-pointer"/></label><p className="font-semibold uppercase tracking-wider pt-1" style={{color:T.txM,fontSize:9}}>Sprite (flips horizontally)</p><div className="flex gap-2">{[["sprite1","Frame 1"],["sprite2","Frame 2"]].map(([k,l])=>{const v=room.player[k];return<div key={k} className="flex-1"><p style={{color:T.txD,fontSize:10}}>{l}</p>{v?<div className="relative group"><img src={v} alt="" className="w-full h-14 object-contain rounded" style={{background:T.bg}}/><button onClick={()=>chgP(k,"")} className="absolute top-0 right-0 p-0.5 rounded-bl opacity-0 group-hover:opacity-100" style={{background:T.dg}}><X size={9} color="#fff"/></button></div>:<button onClick={async()=>{const r=await rF("image/*");if(r)chgP(k,r.data)}} className="w-full h-14 rounded flex items-center justify-center" style={{border:`1px dashed ${T.bd}`,color:T.txM,fontSize:10}}><Upload size={10}/>Upload</button>}</div>})}</div></Sec>
        <Sec title="Audio"><label className="flex items-center justify-between"><span className="text-xs" style={{color:T.txD}}>Mute</span><button onClick={()=>chgR("soundMuted",!room.soundMuted)} className="p-1.5 rounded" style={{background:room.soundMuted?T.dgD:T.scD}}>{room.soundMuted?<VolumeX size={14} color={T.dg}/>:<Volume2 size={14} color={T.sc}/>}</button></label></Sec>
        <Sec title="Room"><label className="flex items-center justify-between"><span className="text-xs" style={{color:T.txD}}>Background</span><input type="color" value={room.bgColor} onChange={e=>chgR("bgColor",e.target.value)} className="w-7 h-5 rounded cursor-pointer"/></label></Sec>
        <Sec title="Cloud"><div className="flex items-center gap-1.5 text-xs" style={{color:cloud.ok?T.sc:T.txM}}>{cloud.ok?<Cloud size={12}/>:<CloudOff size={12}/>}{cloud.ok?"Connected":"Not configured"}</div></Sec>
        <Sec title="Room Management"><div className="flex gap-2"><button onClick={()=>{pH();setRoom(new Rm());setSel(null);dt("Cleared")}} className="flex-1 py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1" style={{background:T.dgD,border:`1px solid ${T.dg}30`,color:T.dg}}><Trash2 size={12}/>Clear</button><button onClick={()=>{pH();setRoom(mkTut());setSel(null);setCamF(true);dt("Tutorial!","success")}} className="flex-1 py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1" style={{background:T.acD,border:`1px solid ${T.acB}`,color:T.ac}}><HelpCircle size={12}/>Tutorial</button></div></Sec>
      </div></div></div>}
    {/* Toolbar */}
    <div className="flex items-center gap-1 px-2.5 py-1.5 flex-shrink-0" style={{background:T.sf,borderBottom:`1px solid ${T.bd}`}}>
      <div className="flex items-center gap-2 mr-2"><div className="w-6 h-6 rounded-md flex items-center justify-center" style={{background:`linear-gradient(135deg,${T.ac},#7c4dff)`}}><Maximize2 size={11} color="#fff"/></div><span className="text-xs font-bold tracking-wider hidden md:inline" style={{color:T.tx}}>ROOM&nbsp;BUILDER</span></div>
      {ed&&<input value={room.roomName} onChange={e=>chgR("roomName",e.target.value)} className="px-2 py-0.5 rounded text-xs font-medium w-24 outline-none hidden sm:block" style={{background:T.bg,border:`1px solid ${T.bd}`,color:T.tx}}/>}
      <div className="w-px h-5 mx-0.5" style={{background:T.bd}}/>
      <Btn onClick={()=>{setEd(p=>!p);setSel(null);setLnk(false)}}>{ed?<><Play size={12}/><span className="hidden sm:inline">Play</span></>:<><Pencil size={12}/><span className="hidden sm:inline">Edit</span></>}</Btn>
      <Btn active={camF} onClick={()=>setCamF(p=>!p)}>{camF?<Camera size={12}/>:<CameraOff size={12}/>}<span className="hidden sm:inline">{camF?"Follow":"Fixed"}</span></Btn>
      {ed&&<><div className="w-px h-5 mx-0.5" style={{background:T.bd}}/><Btn active={room.gridOn} onClick={()=>chgR("gridOn",!room.gridOn)}><Grid3X3 size={12}/></Btn><Btn active={showH} onClick={()=>setShowH(p=>!p)}>{showH?<Eye size={12}/>:<EyeOff size={12}/>}</Btn><div className="w-px h-5 mx-0.5" style={{background:T.bd}}/><Btn onClick={doU}><Undo2 size={12}/></Btn><Btn onClick={doR}><Redo2 size={12}/></Btn>{selId&&<Btn onClick={dupS}><Copy size={12}/></Btn>}</>}
      <div className="flex items-center gap-0.5 ml-1"><Btn onClick={()=>setZoom(z=>Math.max(MIN_Z,z-.2))}><ZoomOut size={12}/></Btn><span className="text-xs w-9 text-center" style={{color:T.txM}}>{Math.round(zoom*100)}%</span><Btn onClick={()=>setZoom(z=>Math.min(MAX_Z,z+.2))}><ZoomIn size={12}/></Btn></div>
      <div className="flex-1"/>
      <Btn onClick={()=>setShowSt(true)}><Settings size={12}/></Btn>
      <div className="relative"><Btn active={showSv} onClick={()=>setShowSv(p=>!p)}><Save size={12}/><span className="hidden sm:inline">Save</span></Btn>{showSv&&<div className="absolute right-0 top-full mt-1 rounded-lg shadow-xl py-1 z-50 min-w-[170px]" style={{background:T.sf,border:`1px solid ${T.bd}`}}>{[{i:<Save size={12}/>,l:"Save Local",a:()=>{Sr.save(rmR.current);dt("Saved!","success");setShowSv(false)}},{i:<Upload size={12}/>,l:"Load Local",a:()=>{const l=Sr.load();if(l){pH();setRoom(l);dt("Loaded!","success")}else dt("None","error");setShowSv(false)}},{i:<Download size={12}/>,l:"Export JSON",a:()=>{Sr.exp(rmR.current,(rmR.current.roomName||"room")+".json");dt("Exported!","success");setShowSv(false)}},{i:<Upload size={12}/>,l:"Import JSON",a:()=>{fR.current?.click();setShowSv(false)}}].map((it,i)=><button key={i} className="w-full flex items-center gap-2.5 px-3 py-2 text-xs hover:brightness-110" style={{color:T.txD}} onClick={it.a}>{it.i}{it.l}</button>)}</div>}</div>
      <Btn onClick={()=>{if(!cloud.ok){dt("Set Supabase creds in code","error");return}setShowSh(true)}}><Cloud size={12}/><span className="hidden sm:inline">Share</span></Btn>
      <Btn className="sm:hidden" onClick={()=>setSb(p=>!p)}><Menu size={12}/></Btn>
    </div>
    {/* Main */}
    <div className="flex flex-1 overflow-hidden relative">
      {ed&&<div className={`flex-shrink-0 flex flex-col overflow-hidden transition-all duration-200 ${sb?"w-56":"w-0 sm:w-56"}`} style={{background:T.sf,borderRight:`1px solid ${T.bd}`}}>
        <div className="flex" style={{borderBottom:`1px solid ${T.bd}`}}>{[["add","Add",<Plus size={12} key="a"/>],["props","Props",<Sliders size={12} key="p"/>]].map(([id,l,ic])=><button key={id} onClick={()=>setTab(id)} className="flex-1 flex items-center justify-center gap-1 py-2 text-xs font-medium" style={{color:tab===id?T.ac:T.txM,borderBottom:tab===id?`2px solid ${T.ac}`:"2px solid transparent"}}>{ic}{l}</button>)}</div>
        {tab==="add"&&<div className="p-3 space-y-2 overflow-y-auto flex-1">
          <p className="font-semibold uppercase tracking-wider" style={{color:T.txM,fontSize:9}}>Objects</p>
          <button onClick={addT} className="w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-medium hover:brightness-110" style={{border:`1px solid ${T.bd}`,color:T.txD}}><Type size={14}/>Text</button>
          <button onClick={addI} className="w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-medium hover:brightness-110" style={{border:`1px solid ${T.bd}`,color:T.txD}}><Image size={14}/>Image / GIF</button>
          <p className="font-semibold uppercase tracking-wider mt-3" style={{color:T.txM,fontSize:9}}>Buttons</p>
          {[{t:BT.PE,l:"Press E",c:"#ef4444",lb:"E",d:"Walk near, press E"},{t:BT.FT,l:"Floor Toggle",c:"#f59e0b",lb:"F",d:"Step on"},{t:BT.FH,l:"Floor Hold",c:"#a855f7",lb:"H",d:"While standing"}].map(b=><button key={b.t} onClick={()=>addB(b.t)} className="w-full flex items-start gap-2.5 px-3 py-2 rounded-lg text-xs hover:brightness-110 text-left" style={{border:`1px solid ${T.bd}`}}><div className="w-5 h-5 rounded-full flex-shrink-0 mt-0.5 flex items-center justify-center text-white font-bold" style={{background:b.c,fontSize:9}}>{b.lb}</div><div><p style={{color:T.txD}} className="font-medium">{b.l}</p><p style={{color:T.txM,fontSize:10}}>{b.d}</p></div></button>)}
          <div className="mt-3 pt-3 space-y-1.5" style={{borderTop:`1px solid ${T.bd}`}}><p className="font-semibold uppercase tracking-wider" style={{color:T.txM,fontSize:9}}>Room</p><SR label="W" value={room.width} onChange={v=>chgR("width",v)} min={400} max={5000} step={100}/><SR label="H" value={room.height} onChange={v=>chgR("height",v)} min={400} max={5000} step={100}/><SR label="Grid" value={room.gridSize} onChange={v=>chgR("gridSize",v)} min={8} max={128} step={8}/></div>
          <div className="mt-3 pt-3" style={{borderTop:`1px solid ${T.bd}`}}><p className="font-semibold uppercase tracking-wider mb-1 flex items-center gap-1" style={{color:T.txM,fontSize:9}}><Layers size={10}/>Objects ({room.objects.length})</p><div className="space-y-0.5 max-h-44 overflow-y-auto">{room.srt().map(o=><button key={o.id} onClick={()=>{setSel(o.id);setTab("props")}} className="w-full flex items-center gap-2 px-2 py-1 rounded text-xs text-left" style={{background:o.id===selId?T.acD:"transparent",color:o.id===selId?T.ac:T.txD}}><span className="w-2.5 h-2.5 rounded-sm flex-shrink-0" style={{background:o.type==="text"?"#22c55e":o.type==="image"?"#3b82f6":"#f59e0b"}}/><span className="truncate flex-1">{o.name}</span>{!o.visible&&<EyeOff size={9} className="opacity-40"/>}<span className="opacity-30 text-[10px]">{o.zIndex}</span></button>)}</div></div>
        </div>}
        {tab==="props"&&<PP obj={selObj} room={room} onChange={chg} onDel={del} onUA={ulnkA} linking={lnk} onTL={()=>setLnk(p=>!p)}/>}
      </div>}
      <div ref={cR} className="flex-1 relative overflow-hidden" style={{cursor:ed?"crosshair":curP?"pointer":"default"}}>
        <canvas ref={cvR} className="w-full h-full block" onMouseDown={onDn} onMouseMove={onMv} onMouseUp={onUp} onMouseLeave={onUp} onWheel={onWh} onTouchStart={e=>{if(e.touches.length===1){const t=e.touches[0];onDn({clientX:t.clientX,clientY:t.clientY})}}} onTouchMove={e=>{if(e.touches.length===1){const t=e.touches[0];onMv({clientX:t.clientX,clientY:t.clientY})}}} onTouchEnd={onUp}/>
        <div className="absolute top-3 left-3 px-2.5 py-1 rounded-md text-xs font-bold tracking-wider select-none" style={{background:ed?T.acD:T.scD,border:`1px solid ${ed?T.acB:`${T.sc}40`}`,color:ed?T.ac:T.sc}}>{ed?"EDITOR":"PLAY"}</div>
        {lnk&&<div className="absolute top-3 left-1/2 -translate-x-1/2 px-4 py-1.5 rounded-lg text-xs font-semibold select-none" style={{background:T.wnD,border:`1px solid ${T.wn}50`,color:T.wn,animation:"pulse 2s infinite"}}>🔗 Click to link/unlink · ESC</div>}
        {!ed&&!mob&&<div className="absolute bottom-3 left-3 px-3 py-1.5 rounded-lg text-xs select-none" style={{background:`${T.sf}dd`,color:T.txD}}><b style={{color:T.tx}}>WASD</b> Move <b style={{color:T.wn}}>E</b> Interact <b style={{color:T.tx}}>Scroll</b> Zoom</div>}
        <div className="absolute bottom-3 right-3 px-2 py-1 rounded text-[10px] select-none" style={{background:`${T.sf}cc`,color:T.txM}}>{Math.round(room.player.x)},{Math.round(room.player.y)} · {Math.round(zoom*100)}%</div>
      </div>
    </div>
    {mob&&!ed&&<DPad onDir={dpH}/>}
    {showSv&&<div className="fixed inset-0 z-40" onClick={()=>setShowSv(false)}/>}
    <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:.7}}`}</style>
  </div></TC.Provider>);
}
